name = "talos/subscription"
version = "0.1.0"
license = "Apache-2.0"
description = "Cardano smart contract-based subscription system for $TALOS token"

[repository]
url = "https://github.com/talos/prorated-sub-service"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github" 