name = "talos/subscription"
version = "0.1.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Cardano smart contract-based subscription system for $TALOS token"

[repository]
user = "talos"
project = "subscription"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[blueprint.parameters]]
name = "talos_policy_id"
type = "ByteArray"
description = "Policy ID for the TALOS token."

[[blueprint.parameters]]
name = "talos_asset_name"
type = "ByteArray"
description = "Asset name for the TALOS token."

[[blueprint.parameters]]
name = "admin"
type = "VerificationKeyHash"
description = "Admin public key hash authorized to receive penalty fees."

[[blueprint.parameters]]
name = "nft_policy_id"
type = "PolicyId"
description = "Policy ID for the Subscription NFT."


[config]
