name = "talos/subscription"
version = "0.1.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Cardano smart contract-based subscription system for $TALOS token"

[repository]
user = "talos"
project = "subscription"
platform = "github"
url = "https://github.com/talos/prorated-sub-service"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[config]
