name = "agent/subscription"
version = "0.1.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Cardano smart contract-based subscription system for $AGENT token"

[repository]
user = "agent"
project = "subscription"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[blueprint.parameters]]
name = "agent_policy_id"
type = "ByteArray"
description = "Policy ID for the AGENT token."

[[blueprint.parameters]]
name = "agent_asset_name"
type = "ByteArray"
description = "Asset name for the AGENT token."

[[blueprint.parameters]]
name = "admin"
type = "VerificationKeyHash"
description = "Admin public key hash authorized to receive penalty fees."

[[blueprint.parameters]]
name = "nft_policy_id"
type = "PolicyId"
description = "Policy ID for the Subscription NFT."


[config]
