import cbor2
import binascii
import json
import sys

# Get the validator CBOR from plutus.json
with open('plutus.json', 'r') as f:
    data = json.load(f)
    validator_cbor = data['validators'][0]['compiledCode']
    minting_cbor = data['validators'][1]['compiledCode']

# Convert hex to binary
validator_bytes = binascii.unhexlify(validator_cbor)
minting_bytes = binascii.unhexlify(minting_cbor)

# CBOR encode the binary
validator_cbor_encoded = cbor2.dumps(validator_bytes)
minting_cbor_encoded = cbor2.dumps(minting_bytes)

# Convert back to hex
validator_cbor_hex = binascii.hexlify(validator_cbor_encoded).decode('utf-8')
minting_cbor_hex = binascii.hexlify(minting_cbor_encoded).decode('utf-8')

# Create the JSON files with proper format
validator_json = {
    "type": "PlutusScriptV3",
    "description": "Subscription Validator - Generated by Aiken",
    "cborHex": validator_cbor_hex
}

minting_json = {
    "type": "PlutusScriptV3", 
    "description": "Subscription Minting Policy - Generated by Aiken",
    "cborHex": minting_cbor_hex
}

# Write to files
with open('subscription.plutus', 'w') as f:
    json.dump(validator_json, f)

with open('mint_policy.plutus', 'w') as f:
    json.dump(minting_json, f)

print("Files created successfully")
